# Generated by Django 4.1.7 on 2025-06-07 21:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('content', models.TextField(max_length=1000, verbose_name='İçerik')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih-Saat')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('text', models.TextField(max_length=1000, verbose_name='Mesaj')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih-Saat')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBlog.post', verbose_name='comments')),
            ],
        ),
    ]
